I fixed the Buggy behavior when you try to read a dacapo ncfile belonging to another user because the current implementation tries to write to the file and you don't normally have permission to do this.
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 36, in read
    calc = Jacapo(ncfile)
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 209, in __init__
    self.set_atoms(self.read_only_atoms(nc))
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 2127, in read_only_atoms
    self.set_psp(sym,psp=pspfile)
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 918, in set_psp
    self.set_status('new')
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 757, in set_status
    nc = netCDF(self.nc,'a')
  File "/usr/local/matsim/lib/python2.5/site-packages/Scientific/IO/NetCDF.py", line 177, in NetCDFFile
    return apply(_NetCDFFile, args)
IOError: netcdf: Permission denied

1. the error first starts when trying to set the status in set_psp
from read_only_atoms
     The way this function is documented, it should not read in
     anything about the pseudopotentials. it should only return the
     atoms, and nothing to do with a calculator.

     I think the solution should be to remove the psp reading code
     from the read_only_atoms function and move it to a new function
     that is called when needed.

     what we need to do is only check for the psp in the ncfile, and
     update the psp database accordingly. nothiing needs to be written
     to the ncfile if nothing is being set.


Step 2:
Index: jacapo.py
===================================================================
--- jacapo.py   (revision 1020)
+++ jacapo.py   (working copy)
@@ -438,6 +438,20 @@

         self.psp = defaultpseudopotentials

+        #update teh pspdatabase from the ncfile if it exists
+        if os.path.exists(self.nc):
+            nc = netCDF(self.nc,'r')
+            sym = nc.variables['DynamicAtomSpecies'][:]
+            symbols = [x.tostring().strip() for x in sym]
+            for sym in symbols:
+                vn = 'AtomProperty_%s' % sym
+                if vn in nc.variables:
+                    var = nc.variables[vn]
+                    pspfile = var.PspotFile
+
+                    self.psp[sym] = pspfile
+            nc.close()
+
     def _set_frame_number(self,frame=None):
         if frame is None:
             nc = netCDF(self.nc,'r')
@@ -2112,19 +2126,19 @@
             mom = nc.variables['InitialAtomicMagneticMoment'][:]
             atoms.set_initial_magnetic_moments(mom)

-        #save the status here, so it can be reset after the psp changes
-        if hasattr(nc,'status'):
-            status = nc.status
-        else:
-            status = None
-        #pseudopotentials
-        for sym in symbols:
-            vn = 'AtomProperty_%s' % sym
-            if vn in nc.variables:
-                var = nc.variables[vn]
-                #this will reset the calculator
-                pspfile = var.PspotFile
-                self.set_psp(sym,psp=pspfile)
+##        #save the status here, so it can be reset after the psp changes
+##        if hasattr(nc,'status'):
+##            status = nc.status
+##        else:
+##            status = None
+##        #pseudopotentials
+##        for sym in symbols:
+##            vn = 'AtomProperty_%s' % sym
+##            if vn in nc.variables:
+##                var = nc.variables[vn]
+##                #this will reset the calculator
+##                pspfile = var.PspotFile
+##                self.set_psp(sym,psp=pspfile)

         #get constraints if they exist
         c = nc.variables.get('constraints',None)
@@ -2134,10 +2148,10 @@

         nc.close()

-        if status is not None:
-            self.set_status(status) # reset status
-        else:
-            self.set_status('None') #old ncfiles do not have a status
+##        if status is not None:
+##            self.set_status(status) # reset status
+##        else:
+##            self.set_status('None') #old ncfiles do not have a status

         return atoms

I still have a permissions error:Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 36, in read
    calc = Jacapo(ncfile)
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 209, in __init__
    self.set_atoms(self.read_only_atoms(nc))
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 701, in set_atoms
    self.write_nc(atoms=atoms)
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 1978, in write_nc
    ncf = netCDF(nc,'a')
  File "/usr/local/matsim/lib/python2.5/site-packages/Scientific/IO/NetCDF.py", line 177, in NetCDFFile
    return apply(_NetCDFFile, args)
IOError: netcdf: Permission denied

I fixed this by explicitly setting the atoms attribute in __init__,
but there is still another error:
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 37, in read
    atoms = calc.get_atoms() #this returns a copy
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 1524, in get_atoms
    atoms.set_calculator(self)
  File "/home/jtest/mypython/ase/ase/atoms.py", line 204, in set_calculator
    calc.set_atoms(self)
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 705, in set_atoms
    self.write_nc(atoms=atoms)
  File "/home/jtest/mypython/ase/ase/calculators/jacapo/jacapo.py", line 1982, in write_nc
    ncf = netCDF(nc,'a')
  File "/usr/local/matsim/lib/python2.5/site-packages/Scientific/IO/NetCDF.py", line 177, in NetCDFFile
    return apply(_NetCDFFile, args)
IOError: netcdf: Permission denied

this is caused by the read function, where the calculator is read in,
but the atoms are returned from get_atoms, which tries to set the
calculator on itself, triggering eventually a set_atoms call.

if I comment that line out, then only a copy of the atoms with no
calculator is returned.

Solution: In the set_atoms method I added code to check if the atoms
are identical to the atoms already stored. if they are, then no change
is made, and no writes are attempted.

No permission errors now when I read other peoples ncfiles!


git-svn-id: https://svn.fysik.dtu.dk/projects/ase/trunk@1024 5af997e4-4c3d-0410-961e-ac0512e437d9